### ISSUE TITLE
Global settings forms for plugins and themes in admin area not shown

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#108]
_From @cvogeley on August 11, 2013 14:46_

for example in the ported impressum addon https://github.com/cvogeley/red-addons/tree/master/impressum the settings form is not shown on the admin page under 
admin/plugins/impressum. I would expect the content created by the function  impressum_plugin_admin_post

I already tried to check if replacing argv(2) back with $a->argv[2] in the following bit would bring it back, but it doesn't.
	case 'plugins':
				if (argc() > 2 && 
					is_file("addon/" . argv(2) . "/" . argv(2) . ".php")){
						@include_once("addon/" . argv(2) . "/" . argv(2) . ".php");
						if(function_exists(argv(2).'_plugin_admin_post')) {
							$func = argv(2) . '_plugin_admin_post';
							$func($a);
						}
				}
				goaway($a->get_baseurl(true) . '/admin/plugins/' . argv(2) );
				return; // NOTREACHED
				break;

It seems like the same issue occurs for themes that use global settings.

_Copied from original issue: friendica/red#93_

**Comment by redmatrix** [comment]
impressum addon does not exist here or in the referenced repository, unable to verify. There was an issue fixed some time ago related to admin plugins. Please create a new issue if there is still a problem.
