### ISSUE TITLE
UI work

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#118]
_From @friendica on April 4, 2014 22:16_

Per Alexandre Hannud Abdo:

Dear @Channel One

Some usability issues we should fix soon, with suggested fixes.

This is feedback from two workshops for over 30 people I held this week, everyone of which registered on my server, created a channel, added each other and exchanged messages. So I'm not not just coming up with a lot of blablabla.

0) The default privacy settings, both the channel and connection settings, should correspond to one of the simple privacy options we give, specifically those labeled as typical. There should also be visual feedback when one selects one of those options, like making it bold and perhaps adding a check mark. The advanced privacy settings button, in fact anything advanced, should not be that much more visible than the rest of the content.

1) Chanview either shouldn't be default, or should have a link on that first column to open the channel as its own page. Also, when looking at an already connected channel it should say "Connected" and provide a link to edit the connection.

2) Pages accessible through channel tabs, like File and Chatrooms, should always display the channel tabs themselves.

3) Clicking on someone's name should always yield the same page, regardless of whether the name is in a comment author header, in a mention, or in a like.

4) Clicking on someone's name, regardless of their privacy settings, should always take you to a page with a link to connect to them, or if already connected, with a link to edit that connection.

5) When browsing an individual image or file, the page should display bbcode for easy copy/paste to properly include it in a message or comment. Would be nice to have that to link to albums as well.

6) The conections link in the navbar (the humanoid figure) should only take you to the new connections page if there are new connections, otherwise it should show all connections.

7) On the connections page, the avatar icons should be links to view the channel, with a separate link to edit the connection.

That's all for now =)

_Copied from original issue: friendica/red#395_

**Comment by jeroenpraat** [comment]
_From @friendica on April 5, 2014 0:47_

6 is done

**Comment by jeroenpraat** [comment]
_From @friendica on April 7, 2014 4:43_

Update: 2,6, and 7 done

**Comment by jeroenpraat** [comment]
_From @solstag on April 8, 2014 2:55_

Seems the fix for 2 is broken.

On both the File and Chatrooms page, instead of seeing the expected tabs for the open channel, I see tabs with links pointing to my channel.

Plus, on the File page, but not on the Chatrooms page, I see the events and bookmarks tabs just as if I had my channel open.

**Comment by jeroenpraat** [comment]
_From @friendica on April 8, 2014 3:1_

...Which is precisely why this was never done previously. It's going to be quite difficult. It should work fine if you visit pages on other sites, but on your own site some of these tabs show up only if you are logged in and they have no concept of who owns the page. Since you are logged in, we show you your page. We have no way of knowing whose channel brought you here.

**Comment by jeroenpraat** [comment]
_From @solstag on April 8, 2014 3:19_

Now I'm a bit confused... if we can and do generate the correct tabs for the channel, about and photos pages, why can't this work for the files and chatrooms pages?

**Comment by jeroenpraat** [comment]
_From @friendica on April 8, 2014 3:22_

Turns out we can. And it has been done.

**Comment by jeroenpraat** [comment]
_From @friendica on April 8, 2014 3:26_

The long story is that I thought ahead that someday we might need to do something like this, and built in the capability (probably around a year ago), but forgot that I had done so.

**Comment by jeroenpraat** [comment]
_From @solstag on April 8, 2014 4:1_

Excellent!

**Comment by jeroenpraat** [comment]
_From @sasiflo on April 11, 2014 9:7_

Is Mike getting old? ;-) Great Job!

**Comment by jeroenpraat** [comment]
_From @solstag on April 14, 2014 16:43_

About 7:

The New Connections page is a bit confusing by the fact that the buttons say "Edit" like in the All Connections page and that now the icon no longer takes you to the edit page. Perhaps in the New Connections page there should be an explanation above the connections like: "Below are your incoming/pending connections, click on Edit to accept or reject them, and other options." Or perhaps the buttons should read "Accept/Reject" instad of "Edit".

About 0:

For incoming new connections, if you click the checkbox to accept the connection, and you are fine with the default settings presented, you'll assume your work is done and won't push the Save button. As a consequence the "good default" settings are never really applied, but the connection leaves the "new connections" list.

I think this automatic behavior of the checkbox is broken, and for new connections we should instead not have that checkbox, but change the "Save" button to an "Accept" or "Connect" button. The connection would only be accepted and leave the new connections list upon submitting the form, which would correctly update the privacy settings. This would also require one less click to approve a connection, with the current two clicks being quite confusing.

As a side note, we're still missing a visual clue of which of the simple settings is picked, if any.

Have a nice week =)

**Comment by jeroenpraat** [comment]
_From @solstag on April 14, 2014 19:29_

About 3:

Is there a reason why links in mentions don't lead to chanview like everything else now does?

There's a good reason why it should: A wants to introduce B to C. So A mentions both in a message. Now any of them should be able to click on the mention and request connection to the other. This is only possible in chanview. And it is a must have for private channels: people are not going to enjoy - let alone figure out - having to copy the link within the mention into the add channel form in the contacts page.

[]s

**Comment by jeroenpraat** [comment]
_From @friendica on April 14, 2014 20:47_

#0 - I'm not following or something is very broken - ticking the "accept" checkbox does not apply until you submit the page - if you don't submit it is left pending. 

> Is there a reason why links in mentions don't lead to chanview like everything else now does?

The links were created on another site which doesn't know where your chanview is or if you even have one. It's just a link in a post. It might not even be a mention of a Red person if you consider the ongoing service federation work.

**Comment by jeroenpraat** [comment]
_From @friendica on April 14, 2014 20:52_

#0 we also display a very prominent box that changes were made and have not yet been submitted. Feel free to improve on this but to claim that it is overly confusing I find a bit surprising if somebody has any attention span whatsoever. Yes there are people who won't follow what's happening, but an orange box popping up saying "changes have been made but not saved" should be self-explanatory to the majority of half-way intelligent folks. .

**Comment by redmatrix** [comment]
This has all been reworked. If there are issues please file a new bug report
