### ISSUE TITLE
Links that are posted to libertree doesn't look too good

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#121]
_From @annando on May 16, 2014 6:40_

When a post goes to libertree, links aren't formatted nicely. Libertree needs another way of treating links.

At the moment it looks like this:
```
#[1](http://www.forbes.com/sites/craigsilver/2014/05/15/funnyball-baseball-statistics-wed-like-to-see/ "") 
```
The libertree parser shows it this way. The title of the link is at the end of the post which doesn't look nice.

In Friendica this works. AFAIK we changed something in the markdownify class.

_Copied from original issue: friendica/red#461_

**Comment by jeroenpraat** [comment]
_From @ghost on May 22, 2014 21:9_

Surely Libertree's UI is a Libertree bug?

**Comment by annando** [comment]
In the meantime we exchanged the markdown libraries in Friendica and it does look good, I think.

**Comment by redmatrix** [comment]
wontfix
