### ISSUE TITLE
proposal for contact inviter

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#124]
_From @xavierle on May 24, 2014 9:4_

this is more an idea of possible additional function than a real issue.

actually social networks grow by invitation amongs friends.

red include actually an invitation function which is indeed working but quite limited : you have to type emails one by one to send the invitations.

many  opensource CMS are using the following piece of code to add plugins for true invitation service (getting emails from webmail providers or other social networks)

http://openinviter.com/

maybe this would be later a good thing to integrated in red.

_Copied from original issue: friendica/red#472_

**Comment by jeroenpraat** [comment]
_From @friendica on May 24, 2014 9:50_

Time and time again we've seen how these email contact lists and email credentials have been mis-used for third-party data collection and spam. I see nothing on this website which gives me any indication of whether or not I should trust them with my email credentials. It's a commercial enterprise so I'm dubious.

I'm not saying "no" but I'm saying perhaps you're trying to sell this to the wrong audience.

**Comment by jeroenpraat** [comment]
_From @friendica on May 24, 2014 9:53_

Not to mention a website/product which seems to have been stagnant since 2009, before the red matrix was even conceived.

**Comment by jeroenpraat** [comment]
_From @xavierle on May 24, 2014 10:6_

to my understanding up to now

openinviter exist as an hosted service and an open source piece of code that can be self hosted and integrated in any other software


i am not recommending to use their offered commercial services but only thinking if this software could be useful as an optional package to red matrix.



but maybe i am wrong and i also shown them only as an exemple

main indea was that the usual function in opensource community script of friend inviters (by webmail contactlist) is a good way to make grow a community

**Comment by jeroenpraat** [comment]
_From @xavierle on May 24, 2014 10:9_

i looked again open inviter it is true it seems quite old now. 
maybe newer invitation librairies are available.

i understand the concern about spam but i was thinking as a self hosted function not external service

**Comment by jeroenpraat** [comment]
_From @friendica on May 24, 2014 10:39_

We could easily ask for the email login details and harvest addresses and additional emails  from your inbox, but we don't do that. We've got the code to do that - if we wanted to use it. It's not a technical problem, it's a trust issue.That's why I suggest that perhaps you're pitching this to the wrong audience. I'm not giving anybody my mailbox login details. Not you, not the red matrix, not Facebook, not Twitter, nobody. If you ask for them, I'm going to wipe your service from my computer so fast it'll make your head spin. 

That is our audience.

**Comment by jeroenpraat** [comment]
_From @xavierle on May 24, 2014 12:8_


I understand your personal opinion.


But as red can be run as a self hosted server i do not see this as a big issue.

 actually we are  starting running a red pod to use for family and friends.

Because there is some enthousiasm about the red concept


But we might also accept that part of the red  audience is not so opposed to any viral function.

Depending how the pod is run, how it is trusted by users and what conditions apply to the credential sharing.

Actually as a couple of friends and relatives, we are finding boring to find each other very manually 
 on the pod we are running by ourselves


And as red is by essence aimed to be self hosted, what is the risk that anyone share its own credential with himself ?




On 24 mai 2014 12:39:40 CEST, RedMatrix <notifications@github.com> wrote:
>We could easily ask for the email login details and harvest addresses
>and additional emails  from your inbox, but we don't do that. We've got
>the code to do that - if we wanted to use it. It's not a technical
>problem, it's a trust issue.That's why I suggest that perhaps you're
>pitching this to the wrong audience. I'm not giving anybody my mailbox
>login details. Not you, not the red matrix, not Facebook, not Twitter,
>nobody. If you ask for them, I'm going to wipe your service from my
>computer so fast it'll make your head spin. 
>
>That is our audience. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/friendica/red/issues/472#issuecomment-44083648

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by jeroenpraat** [comment]
_From @ghost on May 24, 2014 13:7_

The harm is that scraping a mailbox and spamming your friends is morally wrong, poor security practice, and abortive to privacy.

So go ahead, but make it an addon.

**Comment by jeroenpraat** [comment]
_From @xavierle on May 24, 2014 14:0_




>The harm is that scraping a mailbox and spamming your friends is
>morally wrong, poor security practice, and abortive to privacy.


I understand and mainly share this point of view.

But i am not so strong against it.
For example. If you advice directly the persons that they will receive the invitation.

Security issues can always be managed and

Perception of privacy and morality are by essence very personal.



>
>So go ahead, but make it an addon.
>

This is the point since the begining.

Invitation is in no way a core function and does not have to be included in the main red code.


Just something that could be possible through an addon if someone of a group of users enjoys to have it.


Actually it seems i am quite alone thinking that way.

But neither it is  an urgent need

**Comment by jeroenpraat** [comment]
_From @friendica on May 25, 2014 8:14_

If somebody wanted such a thing - a place to start would be to look at the Friendica email connector. There is code there to open your inbox and find stuff in it. Making a list of addresses contained therein is not difficult. I think we assume IMAP, but the same code will work with POP just by changing the mailbox path.

**Comment by jeroenpraat** [comment]
@xavierle This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.

**Comment by xavierle** [comment]
this was more a feature request than a real issue
Le 10 janv. 2016 21:08, "Jeroen van Riet Paap" <notifications@github.com> a
écrit :

**Comment by jeroenpraat** [comment]
A feature request is also an issue. If you think this is still valid for Hubzilla, please recreate your request over there with a reference to this issue.
