### ISSUE TITLE
Facebook RSS-feed with HEX code for æ, ø, å - possible to fix?

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#138]
_From @HaakonME on October 15, 2014 20:25_

Facebok RSS-feeds are broken as Norwegian characters are shown in the RSS feed as HEX code - could be a client issue upon publishing - I do not know.

https://www.facebook.com/feeds/page.php?format=rss20&id=164212400389793

å becomes &xe5; rather than a regular Unicode character or &aring;.

http://www.htmlandphp.com/reference/html-special-characters.html

Is it possible to display these correctly if sourced in Red?

_Copied from original issue: friendica/red#643_

**Comment by jeroenpraat** [comment]
_From @pafcu on October 16, 2014 14:11_

Facebook is messing it up.

The title text is inside a CDATA section, which means that the contained text should not be handled in any special way. This also means that hex codes are not converted to the correct characters. If Facebook didn't put the title text inside CDATA it would work fine. It would also work if Facebook just included the actual character (like in the contents of the posts in the feed) instead of converting them to hex.

The correct solution is to convince Facebook to fix the bug.

**Comment by jeroenpraat** [comment]
_From @pafcu on October 22, 2014 19:27_

You might also have some luck using something like Yahoo! Pipes to fix the Facebook feed. The easiest way to get the feed to work should be adding the attribute "type='html'" to every <title> element. I'm not sure how to do that exactly, though.

**Comment by jeroenpraat** [comment]
_From @friendica on October 23, 2014 2:27_

Our normal conversion and filtering is passing these through intact and they are displayed correctly if passed through these functions manually.
 
What needs to  happen is for somebody to track this text as it goes through the system and find out where it is getting mangled. Somewhere in the system the ampersand is getting encoded and without the appropriate flag to prevent double encoding.

**Comment by jeroenpraat** [comment]
_From @friendica on October 23, 2014 2:41_

Actually I've just tried this feed and all the accents are coming out correctly except for this one post here:

http://www.facebook.com/Fjellskole/posts/533492363461793

The three chars which have difficulty here are not hex encoded but are in fact unicode sequences for which I have no font support.

**Comment by jeroenpraat** [comment]
_From @pafcu on October 24, 2014 10:35_

My mistake, apparently RSS 2.0 expects the content to be encoded, while Atom does the opposite. So the Facebook feed does indeed appear to be valid RSS 2.0. Strangly, Firefox seems to have a bug where it does not decode the entities (as it apparently should).

**Comment by annando** [comment]
The Facebook RSS feed will stop working at June 23 - see here: https://developers.facebook.com/docs/apps/changelog
