### ISSUE TITLE
Warning about unsaved settings is always in English

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#162]
_From @pafcu on January 2, 2015 7:18_

The warning that is displayed when navigating away from a page with unsaved settings is currently always displayed in English.

_Copied from original issue: friendica/red#809_

**Comment by redmatrix** [comment]
For security reasons, can't fix - at least on FF

https://bugzilla.mozilla.org/show_bug.cgi?id=588292
