### ISSUE TITLE
Trimming the body can break item signatures

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#180]
_From @solstag on February 12, 2015 8:45_

In include/items.php, within functions item_store and item_store_update, around lines 1951 and 2454 respectively, we define the body of the item to be stored as ```trim($arr['body'])```.

This has the potential to break signature checking if one receives a post that was not trimmed at the origin.

It is usually not a problem for public posts since those usually get signed in item_store after being trimmed.

It is also usually not a problem for private posts, even though they get singed in ```mod/item.php:item_post```, because they get obscured before being signed. Indeed, the issue hit me in the head because I needed to stop obscuring my posts.

In any case, trimming behavior may vary in other implementations, and we should preserve whatever we get as body since it's the only thing we can verify against the signature.

Besides, trimming breaks ASCII-ART.

I fixed it for myself with a very simple patch for which I'll soon place a pull.

_Copied from original issue: friendica/red#894_

**Comment by solstag** [comment]
Just to keep this up to date, I posted my fix but it was later reverted by Mike, as he decided to keep trimming message bodies.

I still don't understand why trimming is a good idea. As I see it, if we receive something signed we should not mess with it in a way that the signature can no longer be verified. As a member I would expect this to be a strong guarantee: never mess with signed content.

In my opinion could keep a default that we trim stuff on the sender's side, before the signature is applied, but never on the receiving end.

**Comment by jeroenpraat** [comment]
@solstag This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
