### ISSUE TITLE
No message in right corner after registration 

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#184]
_From @jeroenpraat on March 11, 2015 12:19_

When making a test account I noticed that there is no message displayed in the right corner after the registration details are entered. If I remember correctly it first did, telling the person that just registered, that a verification mail is send and he/she should check his/her mailbox.

FYI: Other right-corner-notifications are showed.

_Copied from original issue: friendica/red#924_

**Comment by redmatrix** [comment]
Unable to duplicate. Created accounts with both REGISTER_APPROVE and REGISTER_OPEN and in both cases was presented the appropriate message.

**Comment by git-marijus** [comment]
@jeroenpraat do you still experience this?

**Comment by jeroenpraat** [comment]
Tested it now again with email verify on and off. It works again.
