### ISSUE TITLE
Searching channels in directory doesn't work

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#226]
When I search in the channel directory it gives all channels as a result, but only when the default option 'on this website/hub only' is set. When I disable this option (displaying all r# channels) and when I search again, it works correctly.

**Comment by redmatrix** [comment]
Should be fixed - we'll now over-ride the site/global pref when searching from the navbar (via the search page).

**Comment by jeroenpraat** [comment]
Sorry, doesn't seem to be fixed. Maybe I had to add that it's the search field at the top left on the channel page.

**Comment by jeroenpraat** [comment]
Commit 04959a095etc fixed the search, but now 'this website only' (without searching) gives an empty list.

**Comment by jeroenpraat** [comment]
Check fot yourself https://redmatrix.nl/directory?f=&global=0

**Comment by jeroenpraat** [comment]
Now it's fixed! Thanks!
