### ISSUE TITLE
Registration doesn't work on my host

### ISSUE THREAD

**Issue by Razlo** [redmatrix/redmatrix#321]
Hi there, I haven't found any forum nor mail list, so I post my problem here.
In a fresh updated raspbian (on rpi model B 256MB of RAM, let's see if withstands) I installed redmatrix. Everything went ok until the registration process. After beign told that I have been registered, I'm not logged in and can't do it.

When trying to log in I get two notifications: "Failed authentication" and "Error d'accés." (ca_ES locale).

When doing /ping, I get:
> {"notify":0,"home":0,"network":0,"intros":0,"mail":0,"register":0,"events":0,"events_today":0,"birthdays":0,"birthdays_today":0,"all_events":0,"all_events_today":0,"notice":[],"info":[],"invalid":0}

And if I try to register again, I get a notification warning that "Your email address is already registered at this site".

I also tried with another email from a different domain and a shorter password, but the result was the same.

Asking for a password recovery email is useless, even installing "sendmail" and putting its path to /etc/php5/apache2/php.ini .However, I didn't expect it to work without spending some time learning how does mail work.

What do you say?

**Comment by git-marijus** [comment]
i think by default we send a confirmation email to the registered email address. if you have not got working email on your server you might have not received the email - hence you could not confirm it and are not able to login...
you can try to disable "Verify Email Addresses" in admin/site

**Comment by Razlo** [comment]
The problem is that I haven't been able to even register the admin. Therefore I can't access any administration panel. Is this setting accessible by text configuration?

**Comment by Razlo** [comment]
I finally got mail working, through a new google account (yeah, decentralization is easy! :laughing: ) using ssmtp, which relies al traffic to gmail. I followed this tutorial http://www.debiantutorials.com/installing-ssmtp-mta-mail-transfer-agent/ and added something from https://wiki.debian.org/sSMTP . At first it didn't work because the password had spaces in it, and simple-quoting or \-scaping didn't work, so I changed the password. The resulting config file for ssmtp was:

>mailhub=smtp.gmail.com:587
>UseSTARTTLS=Yes
>AuthUser=mygooglenameaccount
>AuthPass=passwordwithoutspacesnorspecialcharacters
>FromLineOverride=YES
>AuthMethod=LOGIN

I also had to change [this google setting](https://www.google.com/settings/security/lesssecureapps?pli=1), and as read somewhere, logged in via browser so that Google doesn't block my IP.

However, the accounts remain unactivated, and the recovery message looks like this:

> Apreciat/da $username,
>
>	S'ha rebut una sol·licitud en $sitename recentment per restablir
>la teva contrasenya. Per confirmar aquesta sol·licitud, per favor seleccioni l'enllaç de
>verificació sota o copia-ho i pega-ho en la barra d'adreces del teu navegador.
>
>Si NO has sol·licitat aquest canvi, per favor NO segueixis l'enllaç indicat i ignora
>i/o elimina aquest missatge.
>
>La teva contrasenya no es canviarà tret que puguem verificar que ets la teva qui
>va emetre aquesta sol·licitud.
>
>Segueix aquest enllaç per verificar la teva identitat:
>
>$reset_link
>
>A continuació rebràs un missatge amb la nova contrasenya.
>
>Després de accedir, podràs canviar la contrasenya del teu compte a la pàgina de
>configuració.
>
>Les dades d'accés són els següents:
>
>
>Lloc:	$siteurl
>Nom:	$email
>
>
>
>
>Salutacions,
>	L'administració de $sitename

Do you think that it's a translation issue or I am missing some configuration to make it work? I haven't logged in with the administrator, so maybe those are set from the mighty control panel which I desire to reach.

However, now creating new users work, and the received mail is in english and with the proper links and information. I am able to create a channel.

Now, how can I revert the situation of having the admin email "registered" but with its confirmation mail lost in time and space?

Thank you!

**Comment by Razlo** [comment]
Looks like translation is alright:
https://www.transifex.com/projects/p/red-matrix/translate/#ca_ES/lostpass_emltpl/28122377
>Dear {{$username}}, → Apreciat/da {{$username}},

**Comment by redmatrix** [comment]
set account_flags to 0 to indicate the email has been verified and account_roles to 4097 (only do the second for the admin account) in the DB.

The translation appears to be using ca (not ca-es) and that template was never converted to the new format a few years ago. If anybody wants to do this, just put double braces around all the variables e.g. $username becomes {{$username}}

**Comment by Razlo** [comment]
Just for documenting, 'account_roles' was already set to 4096.
>mysql> select account_id, account_created, account_flags, account_roles from account;
>+------------+---------------------+---------------+---------------+
>| account_id | account_created     | account_flags | account_roles |
>+------------+---------------------+---------------+---------------+
>|          1 | 2015-05-15 23:43:49 |             1 |          4096 |
>|          2 | 2015-05-16 00:29:59 |             1 |             0 |
>|          3 | 2015-05-16 15:22:39 |             1 |             0 |
>|          4 | 2015-05-16 15:41:06 |             0 |             0 |
>+------------+---------------------+---------------+---------------+

**Comment by Razlo** [comment]
Regarding to the translation, my browser language is set to "ca", not "ca_ES", so it's ok. However, I think "ca" shouldn't be different to ca_ES. I mean it is fantastic to have ca_ES and ca_ES@val , for instance, but I can't understand "ca" on its own.

Regardless of this, you'll notice a merge request soon fixing it.
My conclusion of this issue is that the mail part should be better documented, having seen that is crucial for a healthy setup. Should it be a requirement of the initial check-list script?

Thank you everybody!

**Comment by redmatrix** [comment]
Working mail is listed as a requirement in install/INSTALL.txt 

There is no easy way to check for working mail from a php script or we would have done so. PHP's mail() function often returns success when mail is delivered to outer space or not delivered at all; since it just passes through /usr/lib/sendmail - if that file exists mail() will almost always returns true; even if your mailer isn't actually setup and configured. You are welcome to figure out a way to verify mail is working but I was so far unsuccessful.

**Comment by Razlo** [comment]
Yeah, actually I realized it after commenting. The only way to check it that I imagine is a centralized one, kind of an "echo server", but with mail. However, if I got it right redmatrix only needs to send mails, not to received them, so the reply should go through a HTTP. It's not easy.

However, there's another way to attack the problem. [Mediagoblin sends by default the emails to a log file](http://mediagoblin.readthedocs.org/en/stable/siteadmin/configuration.html#enabling-email-notifications), so that you can read and follow the links in order to activate the users. You can later modify the config to send real world mails, of course.

It can be useful to keep configuring the hub until you have figured out or decided which way to go for email.

**Comment by Razlo** [comment]
Ok, there you have it https://github.com/redmatrix/redmatrix/pull/324
By the way, there is only one catalan translation, all dialects in one, which is reasonable. Therefore that comment on "ca_ES" or "ca" doesn't apply.
