### ISSUE TITLE
$Projectname and  $projectname is undefined

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#325]
After updating the translations, I get this:

```
PHP Notice:  Undefined variable: Projectname in /var/www/redmatrix/view/nl/strings.php on line ####
```
How to fix this?

**Comment by redmatrix** [comment]
Use single quotes. If you can't use single quotes use a backslash escape \$projectname

**Comment by redmatrix** [comment]
Nope, it's deeper than that. I've just updated po2php so that it handles these correctly.

**Comment by jeroenpraat** [comment]
Thank you Mike. Updated the translation again. Works.
