### ISSUE TITLE
poller.php issue

### ISSUE THREAD

**Issue by tokudan** [redmatrix/redmatrix#339]
Since a couple of hours I get this error for each poller.php run:
PHP Warning:  vsprintf(): Too few arguments in /srv/apache/sites/rm.besaid.de/red/include/dba/dba_driver.php on line 302
PHP Warning:  vsprintf(): Too few arguments in /srv/apache/sites/rm.besaid.de/red/include/dba/dba_driver.php on line 302

That line seems to have last changed in November, so I'm not sure what's happening here.

**Comment by redmatrix** [comment]
That indicates there's an incorrect number of parameters and arguments in an SQL query; probably from some other file. We fixed one of these a week or two ago. Are you running recent code? If so, the offending SQL query will normally be logged into the app logfile if this is configured. You can also log just SQL issues by creating an empty file in your top-level redmatrix directory called dbfail.out and giving permission for the web-server to write to it. If you're not running the most recent code, updating will probably take care of it.

**Comment by tokudan** [comment]
I'm running git master version roughly every 6h.
Meanwhile the problem has not appeared again and I did not have the log file configured, so there's probably not much that can be done to figure out what exactly happened.
