### ISSUE TITLE
this is another joke, I wonder.

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/redmatrix#342]
< Rockybalboa> Good, if you continue with this behavior of spamming users we will eliminate your node, thanks

wtf

http://redmatrix.ml/channel/mama21mama/?f=&mid=fb974020b0dc4630fe2402b617344b5ace8d5d5f545517286b1ba505542bc812@redmatrix.ml&zid=mama21mama%40redmatrix.ml

**Comment by redmatrix** [comment]
Can't follow the conversation or reproduce here. Please provide more detail.

**Comment by mama21mama** [comment]
1 
A stranger enters the chat.
2
I said that spam redmatrix.ml
3
I tell me please pass the spam links
4
responding to what appears above.

with respect to safety:

user system which makes, that I was created.
redmatrix is safe. no one can remove a node so that if. It is a question

**Comment by mama21mama** [comment]
<code>I hes impossible to add your channel</code> > http://legadolibre.com.ar/notice/193981

the threat took effect, I wonder.
