### ISSUE TITLE
it is easier not comment

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/redmatrix#343]
thus the federation breaks.

view > video http://redmatrix.ml/cloud/mama21mama/2.webm
link to source > http://redmatrix.ml/channel/mama21mama/?f=&mid=49c5cf00e72789c0f410ea25d1e73e5ffc047465cb29290f58dffb0706ddca9c@redmatrix.ml&zid=mama21mama%40redmatrix.ml

**Comment by redmatrix** [comment]
You can only comment if the other channel,gives you permission. If there is no comment box, you don't have permission to comment on that channel.

**Comment by mama21mama** [comment]
But it is very hateful permits are by default closed.

**Comment by redmatrix** [comment]
I gather you've never experienced spam.

**Comment by mama21mama** [comment]
Himself administration este servidor. http://mamalibre.com.ar/plus

Why ask me

**Comment by redmatrix** [comment]
The software does not choose the permissions that a channel wishes to use. The channel does. The software enforces whatever choices the channel makes.
