### ISSUE TITLE
multiple channel problems

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/redmatrix#344]
my user: mama21mama@rematrix.ml

redmatrix-es be my second channel on the same account.

![](http://upimage.mamalibre.com.ar/up/c2f0b9a9f31174e44a821f2939bfab7c.png)
![](http://upimage.mamalibre.com.ar/up/1f9dd92bac41d66d1969428d5558b8a4.png)

**Comment by mama21mama** [comment]
I think I found the problem ... a channel may not have the same profile name.

**Comment by redmatrix** [comment]
redmatrix.ml is using an invalid SSL cert. I believe I mentioned that redmatrix requires browser valid certs. You're free to use self-signed certs, but nothing will work.

**Comment by mama21mama** [comment]
It is not a right answer. 
I said that was solved.It was the name of the duplicated profile.
