### ISSUE TITLE
Can't login on my new redmatrix installation

### ISSUE THREAD

**Issue by RogerSik** [redmatrix/redmatrix#357]
Hello,

i installed redmatrix now. 

I see that the user accounts are created in the MariaDB database. But when i try to login (with my password and with the new password from forgotten password email) I get the message that the authentification was'nt successful and I cant login. 

Currently I'm using no SSL certificate (comes later) and in Apache is htaccess activated. puller.php cronjob is also set up. No suhosin is used normal Apache2 + PHP5 (and the required extensions are also installed, says the installation site).

Are there some logs I can see from redmatrix? In Apache I nothing find about login error.  
![2015-06-24 07_25_10-red matrix](https://cloud.githubusercontent.com/assets/165814/8323262/3055cd32-1a42-11e5-9109-368b8dc9db00.png)

Greetings
Roger

**Comment by redmatrix** [comment]
If I recall we're verifying email addresses by default now, so we would have sent a verification email for you to activate the account. Perhaps that got lost in the spam folder or for whatever reason was never received. You can probably set the account_flags to 0 in the DB for that account and this should make the account "verified" and allow you to login.

**Comment by RogerSik** [comment]
Hey yes i was first setting up redmatrix and then my email system configuration after I found out that the password forgett function doens't sent emails.

Thanks for your tipp with account_flags that helped me.
