### ISSUE TITLE
Unable to obtain post information from database.

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/redmatrix#362]
In this message when trying to create a post should be.

**Comment by mama21mama** [comment]
fuck > https://my.federated.social/channel/tazman/?f=&mid=5d41d294f2dd1e971c00cf726be889abe8e81a70bd55e908c9d02e87fd736dec@my.federated.social

same problem.

**Comment by mama21mama** [comment]
redmatrix the code think it's very unstable. with storage in SQL.

**Comment by mama21mama** [comment]
Free Stone .... now because there will be damaged is a good question.

mysqldump: Got error: 144: Table './redmatrix/item' is marked as crashed and last (automatic?) repair failed when using LOCK TABLES

**Comment by mama21mama** [comment]
grrr solved

mama@zeuza:/var/lib$ sudo -u mysql myisamchk -r -v mysql/redmatrix/item
[sudo] password for mama: 
- recovering (with sort) MyISAM-table 'mysql/redmatrix/item'
Data records: 0
- Fixing index 1
  - Searching for keys, allocating buffer for 149745 keys
  - Dumping 17701 keys
- Fixing index 2
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 3
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 4
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 5
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 6
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 7
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 8
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 9
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 10
  - Searching for keys, allocating buffer for 2695 keys
  - Last merge and dumping keys
- Fixing index 11
  - Searching for keys, allocating buffer for 2695 keys
  - Last merge and dumping keys
- Fixing index 12
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 13
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 14
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 15
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 16
  - Searching for keys, allocating buffer for 2695 keys
  - Last merge and dumping keys
- Fixing index 17
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 18
  - Searching for keys, allocating buffer for 2695 keys
  - Last merge and dumping keys
- Fixing index 19
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 20
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 21
  - Searching for keys, allocating buffer for 2695 keys
  - Last merge and dumping keys
- Fixing index 22
  - Searching for keys, allocating buffer for 7824 keys
  - Last merge and dumping keys
- Fixing index 23
  - Searching for keys, allocating buffer for 7824 keys
  - Last merge and dumping keys
- Fixing index 24
  - Searching for keys, allocating buffer for 7709 keys
  - Last merge and dumping keys
- Fixing index 25
  - Searching for keys, allocating buffer for 2695 keys
  - Last merge and dumping keys
- Fixing index 26
  - Searching for keys, allocating buffer for 2695 keys
  - Last merge and dumping keys
- Fixing index 27
  - Searching for keys, allocating buffer for 2695 keys
  - Last merge and dumping keys
- Fixing index 28
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 29
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 30
  - Searching for keys, allocating buffer for 17702 keys
  - Dumping 17701 keys
- Fixing index 31
  - Searching for keys, allocating buffer for 18708 keys
  - Last merge and dumping keys
- Fixing index 32
  - Searching for keys, allocating buffer for 18708 keys
  - Merging 620878 keys
  - Last merge and dumping keys
- Fixing index 33
  - Searching for keys, allocating buffer for 18708 keys
  - Dumping 0 keys
- Fixing index 34
  - Searching for keys, allocating buffer for 18708 keys
  - Dumping 54 keys
- Fixing index 35
  - Searching for keys, allocating buffer for 18708 keys
  - Dumping 0 keys
- Fixing index 36
  - Searching for keys, allocating buffer for 18708 keys
  - Dumping 0 keys
Data records: 17701


http://stackoverflow.com/questions/8843776/mysql-table-is-marked-as-crashed-and-last-automatic-repair-failed

**Comment by jeroenpraat** [comment]
@mama21mama This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
