### ISSUE TITLE
mysql warning in table `term`: Field 'imgurl' doesn't have a default value

### ISSUE THREAD

**Issue by solstag** [redmatrix/redmatrix#366]
would probably be nice to give it a default

**Comment by redmatrix** [comment]
Both install/schema_mysql.sql and install/schema_postgres.sql contain a DEFAULT '' for that field. Where are you looking? Note: I do see several other things in that table which don't have a default on postgres but do on mysql. imgurl is not one of them.

Another note: Adding defaults to all fields which didn't have them happened around 1-2 years ago so it's possible your database creation preceded that. At this point you might be better off finding the mysql config that sets strict default checking and disabling it than going through every column that changed when we fixed this.

**Comment by solstag** [comment]
Thanks, that's probably the case and I'll check that. It hadn't occurred to me that default was set a long time ago and things might have been fixed, so I didn't even look at the code, sorry for the improper bug. Closing now =)
