### ISSUE TITLE
In Android Browser -> wrong Appearance and Image Upload

### ISSUE THREAD

**Issue by matzestefan** [redmatrix/redmatrix#368]
# Appearance on Mobile Devices
I've installed the newest version (2.6) of RedMatrix today and I have tried to use it on a mobile device. The first problem is that there are some buggy appereances on channels and so on. There is much empty space on the right side, that is not used. So the channel seems to be a very small vertical line. When you click in a Input Element then it's alright and the elements takes the whole width.

# Image Upload
The other Problem is that i can not upload images with my Android Phone.
Samsung Galaxy S2
OS: Replicant 4.2

**Comment by jeroenpraat** [comment]
Can you tell me your browser and version? I slightly remember there was a similar sounding issue with a particular Android browser.

**Comment by git-marijus** [comment]
I can't duplicate here browser version 4.4.4
What version of the browser are you using?

**Comment by matzestefan** [comment]
i have two different browsers:
[Tint Browser](https://f-droid.org/repository/browse/?fdfilter=Tint&fdid=org.tint)
[OrWeb Browser](https://f-droid.org/repository/browse/?fdfilter=orweb&fdid=info.guardianproject.browser)
Standard Android Browser: I couldn't find a version number :( it might be very old, because its apperantly not in the F-Droid Repository. 

But the other two browsers do not work, too. Dou you recommend a different browser use (it should be on F-Droid market)?

**Comment by matzestefan** [comment]
oh sorry, i forgot the versions.
Orweb: Version 0.6.1
Tint: 1.8

**Comment by git-marijus** [comment]
do you have javascript enabled?

**Comment by matzestefan** [comment]
in tint it is enabled, in Orweb it wasn't. I will  check it again with enabled javascript in a few minutes

**Comment by git-marijus** [comment]
tint 1.8 looks fine here...

**Comment by matzestefan** [comment]
@git-marijus maybe you can have a look at [my installation](https://red.dazlious.de) and check if the login page is displayed correctly?

**Comment by git-marijus** [comment]
yes... works fine at your installation... login and channel... 
might want to try clearing cache...

**Comment by matzestefan** [comment]
clearing cache has no success. I've tried to install firefox browser but it has crashed directly after launching. 

I think i will let friends test the site and we will see, if they have the same problems. 

Thankyou for your help. @git-marijus One last question: Are you able to upload fotos with your mobile browser?

**Comment by jeroenpraat** [comment]
Tested it with the latest Firefox and Tint with Cyanogenmod 12 without problems.

**Comment by matzestefan** [comment]
maybe my OS is the bad guy ;)

**Comment by tonybaldwin** [comment]
looks fine with latest Dolphin browser (acquired with Aptoid, F-Droid being buggy and unable to grab Dolphin or Firefox today).

**Comment by jeroenpraat** [comment]
@matzestefan This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
