### ISSUE TITLE
Blocked Admin - how unblocking? :(

### ISSUE THREAD

**Issue by matzestefan** [redmatrix/redmatrix#371]
I did something embarrassing. Accidentally i have blocked my own admin account in the admin menu and now i'm not able to login again.

I have now opend the .htconfig.php and have changed there the admin mail adress after that i created with that new mail adress a new account at Red#Matrix, but i do net get access to the admin menu. 

I tried to restart the php-cgi process, but nothing have changed. I have also searched in the MYSQL database but i could not found the flag that shows which user is blocked and which not.

What can i do? Please help!

**Comment by redmatrix** [comment]
In your database, set account.account_flags = 0 for that account.

**Comment by matzestefan** [comment]
Thankyou, it have worked!
