### ISSUE TITLE
Poller.php can't find boot.php

### ISSUE THREAD

**Issue by mehronkugler** [redmatrix/redmatrix#379]
It seems the poller.php file is having problems opening boot.php.

I have the following lines in my Apache error logs:

PHP Warning:  require_once(boot.php): failed to open stream: No such file or directory in /redmatrix/include/poller.php on line 3
PHP Fatal error:  require_once(): Failed opening required 'boot.php' (include_path='.:<censored>') in /redmatrix/include/poller.php on line 3

Boot.php is read/write/executable by user and group (-rwxrwxr-x)

When I attempt to manually run /usr/bin/php include/poller.php from the command line I get the following console error:

Status: 500 Internal Server Error
Content-type: text/html

Any ideas? Environment variable issue? I have a working PHP_PATH variable. I am on a shared hosting environment.

**Comment by redmatrix** [comment]
Status: 500 Internal Server Error
    Content-type: text/html

These lines indicate to me that the version of php that you are invoking was built as a cgi, and probably isn't a standalone command line version. The cgi probably resets the current working directory somehow when it is started, leading to the inability to find boot.php in the current directory. I seem to recall there was a way to determine if you had a cmdline php or a cgi php by invoking it with '-v' (to obtain the version info), but it has been quite some time and I don't recall precisely what it is you should be looking for. I would probably ask your hosting provider or hosting support forum where to find a (specifically) command line version of php.

**Comment by mehronkugler** [comment]
Thanks very much for your reply. I looked into it and it seems to be exactly that. I found the correct flags for my PHP binary to be able to run stuff from the command line, I was able to run the poller without any errors. Will see if the issue persists but I think for now it's solved.
