### ISSUE TITLE
Response from remote channel was incomplete.

### ISSUE THREAD

**Issue by mehronkugler** [redmatrix/redmatrix#380]
Hi again,

I get this error when attempting to connect with (add channels as "friends") on my own hub. I also get very long timeouts when posting on other channels on my hub, or attempting to reply to a post on another channel, also on my hub.

Hoping to see where I can start poking around in terms of determining what is not configured correctly on my server in order to fix this issue. What settings should I be looking at? Please let me know what info I should provide. 

Thanks in advance.

**Comment by redmatrix** [comment]
> Please let me know what info I should provide. 

The server url and probably the nickname/username of a valid channel so we can probe it and see. You could also use the /probe utility on your site and see for yourself what is being returned. It should be a json array representing the channel.

**Comment by mehronkugler** [comment]
Hi again,

Thanks for the followup. My server is https://social.level11.us . I probed level11teatime@social.level11.us , but I didn't get a JSON reply. I did get an array, but it doesn't look like JSON. Sample output:

`[name] => Level 11 Social Admin
    [name_updated] => 2015-07-20 23:09:29
    [address] => level11teatime@social.level11.us
    [photo_mimetype] => image/png
    [photo] => https://social.level11.us//photo/profile/l/2
    [photo_updated] => 2015-07-26 22:35:23
    [url] => https://social.level11.us//channel/level11teatime
    [connections_url] => https://social.level11.us//poco/level11teatime`

**Comment by redmatrix** [comment]
Sorry, we convert the json to a php array for display - but that looks correct. I'm seeing nothing wrong here; except if I attempt a "magic-auth" from my site it goes into an endless loop. Oh wait - it seems all the URLs have double slashes, so the site url likely has a trailing slash and this might be throwing stuff off. 

Try this:

% util/config system baseurl

and see if there's a slash at the end. If so, 

% util/config system baseurl https://social.level11.us

to fix it. The first web access after you do this will go through and try to fix all the urls in the db, so just let it run (don't try to stop the page).

**Comment by mehronkugler** [comment]
Thanks very much. I'll give it a try. Again pardon my cluelessness, what does the % indicate? php console of some sort?

**Comment by redmatrix** [comment]
Shell prompt - I'm hoping you have Linux or similar shell access. Enter the part after the % from your top-level website directory.

**Comment by mehronkugler** [comment]
Got it. I do have shell access. I ran the commands you indicated above, had to use -q option (php -q) as recommended by my webhost. It didn't seem to generate any console output, so I went into .htconfig.php and modified the baseurl variable manually, removed the trailing slash from the end. 

Upon refreshing my browser connection to the server (letting things load), I still find very long response times persist when trying to "connect" with other channels on my hub.

Unfortunately I must have borked something, I'm just getting 500 errors now.

**Comment by redmatrix** [comment]
Once stored in the DB we no longer use the config variable from the config file. You could try to edit the entry in the config table with phpmyadmin.

**Comment by mehronkugler** [comment]
Thanks for the tip. I deleted a duplicate "site_url" key in the "site" table, one with a trailing slash.

Are you able to connect to the  level11teatime@social.level11.us or probe it successfully now?

**Comment by redmatrix** [comment]
That worked for me.

**Comment by jeroenpraat** [comment]
@mehronkugler This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
