### ISSUE TITLE
Feature Request: Ability to remove accounts & channels in bulk.

### ISSUE THREAD

**Issue by gellenburg** [redmatrix/redmatrix#386]
**Problem:** The /admin/users page allows the site admin to block or delete an account through the use of the block or delete icons on each line for each account.

Clicking these buttons pops up a dialog box asking the admin if they are sure they want to delete the item, warning that all posts will be deleted as well.

This dialog box makes it next to impossible to delete more than one account every few seconds, and requires mouse movements and keyboard presses to dismiss the ensuing dialog box.

**Suggested Behavior:** Include a selectable flag on the page that, if true, displays no confirmation, speeding up the deletion process.

**Problem:** There is no way to select more than one row at a time on the /admin/users page.

**Suggested Behavior:** Include check-boxes on each row to allow the site admin to select multiple rows at once, so (s)he can then take advantage of the "delete" and "block" buttons at the bottom of the page.

**Problem:** The "select all" hyperlink at the bottom of the /admin/users page is ineffective.

**Suggested Behavior:** Enable the "select all" link to select all rows on the page.

**Alternately…** provide some mechanism via the command-line for the site admin to script and delete multiple accounts and/ or channels by supplying an argument (perhaps the account id integer or some other GUID).

Thanks!

**Comment by redmatrix** [comment]
It appears the checkboxes went missing after a recent change to that page.

**Comment by gellenburg** [comment]
Thanks for fixing. :smile_cat:
