### ISSUE TITLE
Table Session errors BUG

### ISSUE THREAD

**Issue by royalterra** [redmatrix/redmatrix#402]
HI I try with new installations and different test in Pod , nodes ... have a constant traffic I got always after some time crash in table session .
This error is check with MYSQL and with MARIADB 
With PHPmyadmin repair REPAIR TABLE `session` some times is OK other times become impossible. Temporally solution to restart the server to production again is stop MYSQL
go to 
/var/lib/mysql/YOURDATABASE_Name
Execute: myisamchk -r -v -f session
That show after
- recovering (with sort) MyISAM-table 'session'
Data records: 14
- Fixing index 1
  - Searching for keys, allocating buffer for 60 keys
  - Dumping 14 keys
- Fixing index 2
  - Searching for keys, allocating buffer for 15 keys
  - Dumping 14 keys
- Fixing index 3
  - Searching for keys, allocating buffer for 15 keys
  - Dumping 14 keys

After That start MYSQL again 
service mysql start
[ ok ] Starting MariaDB database server: mysqld . . ..
and EXECUTE myisamchk -e *.MYI

that will solve the problem temporally or some times the error start after 5 minutes

**Comment by jeroenpraat** [comment]
This is a known issue. It is also as good as resolved in Hubzilla (no session table crashes has been reported).

So I advice you to make a cronjob that checks for a crashed session table and automatically truncates it when that happens, OR just forget Redmatrix and go with Hubzilla.

**Comment by jeroenpraat** [comment]
You can put this in a script in your root folder (chmod 700 on it) and add it as a cronjob (as root) every 5 minutes. Adjust it to your configuration. It's tested on Debian 8 with MariaDB. I use it in redmatrix.nl. 

````bash
touch /var/www/redmatrix/dbfail.out
chown www-data:www-data /var/www/redmatrix/dbfail.out
if fgrep crashed /var/www/redmatrix/dbfail.out; then
mysql -uUSER -pPASSWORD -Dredmatrix -B -e "repair table session"
sleep 3
rm /var/lib/mysql/redmatrix/session.TMM
sleep 3
mysql -uUSER -pPASSWORD -Dredmatrix -B -e "truncate table session"
sleep 2
rm /var/www/redmatrix/dbfail.out
touch /var/www/redmatrix/dbfail.out
chown www-data:www-data /var/www/redmatrix/dbfail.out
mail -s "Redmatrix: session table crashed" "YOUREM@IL" <<EOF
Redmatrix: session table crashed, but it is automatically fixed! Hooray!
EOF
fi
````
